### PR TITLE
New: support an array of templates to create multiple releases at once

### PR DESCRIPTION
**Pull request by cbackas**
### Description
Allow an array of release templates to be provided to the `releaseNameTemplate` config variable, then make multiple Jira versions and add them all as fixVersions to the issue. Also new template variables for the release names! major, minor, patch, channel

### This is a 

- [ ] Bug Fix
- [X] Feature
- [ ] Documentation
- [ ] Other

#### Commit style
   
   - [ ] Changes are on a branch with a descriptive name eg. `fix/missing-queue`, `docs/setup-guide`
   
   - [ ] Commits start with one of `feat:` `fix:` `docs:` `chore:` or similar
   
   - [ ] No excessive commits, eg: there should be no `fix:` commits for bugs that existed only on the PR branch (see [guide-to-interactive-rebasing](https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d))

#### Protected files

The following files should not change unless they are directly a part of your change.
    
   - [ ] `yarn.lock` (unless package.json is also modified, then only the new/updated package should be changed here)
   
   - [ ] `package.json` (renovate bot should handle all routine updates)
   
   - [ ] `tsconfig.json` (only make it stricter, making it more lenient requires more discussion)
   
   - [ ] `tslint.json` (only make it stricter, making it more lenient requires more discussion)

### CODE REVIEW

**Comment by cbackas** [comment]
@dylanhitt im back :)

**Comment by dylanhitt** [comment]
Hey @cbackas seems I should ask GitHub to unfork soon 😅

I'll take a look tomorrow or Friday. If I haven't got there feel free to bother me. Let me know if it's urgent.

**Comment by dylanhitt** [comment]
Oh thought i had did this

**Review by dylanhitt — APPROVED** [review]
Looks good

**Comment by dylanhitt** [comment]
ope, seems the linter is angry: https://github.com/dylanhitt/semantic-release-jira/actions/runs/5381343246/jobs/9765279998

If you want to fix feel free or I'll get them in the AM and add a job to text on PRs. So that doesn't happen again.

**Pull request merged**
